#' Generate a structured sensitivity analysis report
#'
#' @description
#' Produces a complete, structured report from a \code{sens_results} object.
#' The report includes study design, numeric results, fragility classification,
#' narrative interpretation, and suggested reporting language for academic papers.
#'
#' Works fully offline without an API key. If \code{interpret_sensitivity()}
#' has not been run, the function runs it automatically using template-based
#' narratives.
#'
#' @param x A \code{sens_results} object, ideally with fragility assessed.
#' @param format Character. Output format. One of \code{"markdown"},
#'   \code{"text"}. Default \code{"markdown"}.
#' @param include_citation Logical. Append reference list. Default \code{TRUE}.
#' @param verbosity Character. Narrative verbosity passed to
#'   \code{interpret_sensitivity()} if narrative not yet generated.
#'   Default \code{"standard"}.
#' @param file Character. Optional file path to write the report.
#'   If \code{NULL} (default), returns the report as a character string
#'   and prints it.
#'
#' @return Invisibly returns the report as a character string.
#'   If \code{file} is specified, also writes to disk.
#'
#' @examples
#' \donttest{
#' res <- new_sens_results(
#'   design = "regression", treatment = "directlyharmed",
#'   outcome = "peacefactor", frameworks = c("sensemakr", "evalue"),
#'   results = list(
#'     sensemakr = list(estimate = 0.097, r2yd_x = 0.022,
#'                      rv_q = 0.139, rv_qa = 0.076),
#'     evalue    = list(estimate = 0.097, evalue = 1.90,
#'                      evalue_lower = 1.55)
#'   ),
#'   fragility = list(point = "Stable", alpha = "Moderately fragile",
#'                    point_label = "RV = 13.9%", alpha_label = "RV = 7.6%")
#' )
#' report <- generate_report(res)
#' cat(report)
#' }
#'
#' @export
generate_report <- function(x,
                            format           = c("markdown", "text"),
                            include_citation = TRUE,
                            verbosity        = "standard",
                            file             = NULL) {

  if (!is_sens_results(x)) {
    rlang::abort("`x` must be a `sens_results` object.")
  }

  format <- match.arg(format)

  # run interpretation if not done yet
  if (is.null(x$narrative)) {
    x <- interpret_sensitivity(x, verbosity = verbosity)
  }

  # build report sections
  sections <- list()

  if (format == "markdown") {
    sections <- .build_markdown_report(x, include_citation)
  } else {
    sections <- .build_text_report(x, include_citation)
  }

  report <- paste(sections, collapse = "\n\n")

  # write to file if requested
  if (!is.null(file)) {
    writeLines(report, file)
    cli::cli_alert_success("Report written to: {file}")
  } else {
    cat(report, "\n")
  }

  invisible(report)
}


# ==============================================================================
# Markdown report builder
# ==============================================================================

.build_markdown_report <- function(x, include_citation) {

  ts  <- format(x$timestamp, "%Y-%m-%d %H:%M")
  fws <- paste(toupper(x$frameworks), collapse = ", ")

  sections <- list()

  # --- Title ---
  sections$title <- paste0(
    "# Sensitivity Analysis Report\n",
    "_Generated by causalfrag | ", ts, "_"
  )

  # --- Study Design ---
  sections$design <- paste0(
    "## Study Design\n\n",
    "| Field | Value |\n",
    "|---|---|\n",
    "| Design | ", x$design, " |\n",
    "| Treatment | `", x$treatment, "` |\n",
    "| Outcome | `", x$outcome, "` |\n",
    "| Frameworks run | ", fws, " |"
  )

  # --- Numeric Results ---
  num_lines <- "## Numeric Results\n"

  if ("sensemakr" %in% x$frameworks) {
    r <- x$results$sensemakr
    num_lines <- paste0(num_lines, "\n### Cinelli & Hazlett (2020) -- sensemakr\n\n",
      "| Statistic | Value |\n|---|---|\n",
      .md_row("Estimate",                       r$estimate,  4),
      .md_row("Partial R\u00b2 (treat-outcome)", r$r2yd_x,   4),
      .md_row("Robustness Value (q = 1)",        r$rv_q,     4),
      .md_row("Robustness Value (q = 1, a = .05)", r$rv_qa,  4)
    )
  }

  if ("evalue" %in% x$frameworks) {
    r <- x$results$evalue
    num_lines <- paste0(num_lines, "\n### VanderWeele & Ding (2017) -- E-value\n\n",
      "| Statistic | Value |\n|---|---|\n",
      .md_row("Estimate",          r$estimate,     4),
      .md_row("E-value (point)",   r$evalue,       4),
      .md_row("E-value (CI lower)", r$evalue_lower, 4)
    )
  }

  if ("itcv" %in% x$frameworks) {
    r <- x$results$itcv
    num_lines <- paste0(num_lines, "\n### Frank (2000) -- ITCV / konfound\n\n",
      "| Statistic | Value |\n|---|---|\n",
      .md_row("ITCV index",                r$itcv,    4),
      .md_row("Robustness of Inference",   r$rir,     0, suffix = " cases"),
      .md_row("Percent bias to invalidate", r$pct_bias, 1, suffix = "%")
    )
  }

  sections$numeric <- num_lines

  # --- Fragility ---
  frag <- x$fragility
  if (!is.null(frag)) {
    frag_lines <- "## Fragility Classification\n\n| Dimension | Level |\n|---|---|\n"
    if (!is.null(frag$point)) {
      frag_lines <- paste0(frag_lines,
        "| Point estimate nullification | **", frag$point, "** |\n",
        "| Statistical significance (a = .05) | **", frag$alpha %||% "not assessed", "** |\n"
      )
      if (!is.null(frag$point_label) && nchar(frag$point_label) > 0)
        frag_lines <- paste0(frag_lines, "\n> ", frag$point_label, "\n")
      if (!is.null(frag$alpha_label) && nchar(frag$alpha_label) > 0)
        frag_lines <- paste0(frag_lines, "\n> ", frag$alpha_label, "\n")
    }
    sections$fragility <- frag_lines
  }

  # --- Narrative ---
  if (!is.null(x$narrative)) {
    src <- if (x$llm_used) "_LLM-assisted_" else "_Template-based_"
    sections$narrative <- paste0(
      "## Narrative Interpretation\n\n",
      x$narrative, "\n\n",
      src, " interpretation."
    )
  }

  # --- Suggested Reporting Language ---
  sections$reporting <- paste0(
    "## Suggested Reporting Language\n\n",
    "Include the following in your paper's methods or results section:\n\n",
    "> ", x$narrative %||% "[Run interpret_sensitivity() first]"
  )

  # --- CFI section ---
  if (!is.null(x$cfi)) {
    cfi <- x$cfi
    comp_rows <- paste(sapply(names(cfi$components), function(nm) {
      label <- switch(nm, rv="RV (point est.)", rv_alpha="RV (significance)",
                      evalue="E-value", pct_bias="Pct bias (ITCV)", nm)
      paste0("| ", label, " | ", round(cfi$components[[nm]], 1), " |\n")
    }), collapse = "")

    sections$cfi <- paste0(
      "## Causal Fragility Index (CFI)\n\n",
      "**Overall CFI: ", cfi$score, " / 100 -- ", cfi$label, "**\n\n",
      "| Component | Score (0-100) |\n|---|---|\n",
      comp_rows,
      "\n> ", cfi$interpretation
    )
  }

  # --- Cross-framework summary ---
  if (length(x$frameworks) > 1L) {
    sections$triangulation <- paste0(
      "## Cross-Framework Summary\n\n",
      "Across the ",
      paste(toupper(x$frameworks), collapse = ", "),
      " frameworks, the results converge on a consistent interpretation: ",
      "the estimated association between `", x$treatment, "` and `", x$outcome,
      "` is **", tolower(frag$point %||% "not assessed"), "** with respect to ",
      "point-estimate nullification, but **",
      tolower(frag$alpha %||% "not assessed"),
      "** with respect to statistical significance at alpha = .05. ",
      "Triangulation across multiple frameworks strengthens confidence in this classification."
    )
  }

  # --- Citations ---
  if (include_citation) {
    cite_lines <- "## References\n"
    if ("sensemakr" %in% x$frameworks)
      cite_lines <- paste0(cite_lines,
        "\nCinelli, C., & Hazlett, C. (2020). Making sense of sensitivity: ",
        "Extending omitted variable bias. *Journal of the Royal Statistical ",
        "Society: Series B*, 82(1), 39-67. https://doi.org/10.1111/rssb.12348\n")
    if ("evalue" %in% x$frameworks)
      cite_lines <- paste0(cite_lines,
        "\nVanderWeele, T. J., & Ding, P. (2017). Sensitivity analysis in ",
        "observational research: Introducing the E-value. *Annals of Internal ",
        "Medicine*, 167(4), 268-274. https://doi.org/10.7326/M16-2607\n")
    if ("itcv" %in% x$frameworks)
      cite_lines <- paste0(cite_lines,
        "\nFrank, K. A. (2000). Impact of a confounding variable on the inference ",
        "of a regression coefficient. *Sociological Methods & Research*, 29(2), ",
        "147-194. https://doi.org/10.1177/0049124100029002001\n")
    cite_lines <- paste0(cite_lines,
      "\nHait, S. (2026). causalfrag: A cross-framework causal fragility index ",
      "of sensitivity analysis for unmeasured confounding. R package version 0.1.0.")
    sections$citations <- cite_lines
  }

  sections
}


# ==============================================================================
# Plain text report builder
# ==============================================================================

.build_text_report <- function(x, include_citation) {

  ts  <- format(x$timestamp, "%Y-%m-%d %H:%M")
  sep <- paste(rep("-", 60), collapse = "")

  sections <- list()

  sections$title <- paste0(
    "SENSITIVITY ANALYSIS REPORT\n", sep, "\n",
    "Generated by causalfrag | ", ts
  )

  sections$design <- paste0(
    "STUDY DESIGN\n", sep, "\n",
    "Design:     ", x$design, "\n",
    "Treatment:  ", x$treatment, "\n",
    "Outcome:    ", x$outcome, "\n",
    "Frameworks: ", paste(toupper(x$frameworks), collapse = ", ")
  )

  if (!is.null(x$narrative)) {
    sections$narrative <- paste0(
      "NARRATIVE INTERPRETATION\n", sep, "\n",
      x$narrative
    )
  }

  if (!is.null(x$fragility)) {
    sections$fragility <- paste0(
      "FRAGILITY\n", sep, "\n",
      "Point estimate:      ", x$fragility$point %||% "not assessed", "\n",
      "Significance:        ", x$fragility$alpha %||% "not assessed"
    )
  }

  sections$footer <- paste0(
    sep, "\n",
    "Full sensitivity outputs available in the supplementary materials.\n",
    "Statistical results computed by transparent R functions.\n",
    "LLM used for narrative: ", x$llm_used
  )

  sections
}


# ==============================================================================
# Helper: markdown table row with safe formatting
# ==============================================================================

.md_row <- function(label, value, digits = 4, suffix = "") {
  if (is.null(value) || length(value) == 0L || is.na(suppressWarnings(as.numeric(value)))) {
    return(paste0("| ", label, " | NA |\n"))
  }
  v <- as.numeric(value)
  formatted <- if (digits == 0) {
    paste0(as.integer(round(v)), suffix)
  } else {
    paste0(round(v, digits), suffix)
  }
  paste0("| ", label, " | ", formatted, " |\n")
}
